events { }
http {
    upstream video_api {
        least_conn;
        server app_server_1:80;
        server app_server_2:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://video_api;
        }
    }
}